name: Run tests

on: [push, pull_request]

env:
  PACKAGE: GitSavvy
  UNITTESTING_TAG: master
  TRAVIS_OS_NAME: linux

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        st_version: [3, 4]
    container:
      image: sublimetext/unittesting
      options: --cap-add=NET_ADMIN
    env:
      SUBLIME_TEXT_VERSION: ${{ matrix.st_version }}
    steps:
      - uses: actions/checkout@v1
      - run: |
          git config --global user.name GitSavvy
          git config --global user.email gitsavvy@gitsavvy.com
      - run: sh -e /etc/init.d/xvfb start
      - run: curl -OL https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/github.sh
      - run: |
          PATH="$HOME/.local/bin:$PATH"
          sh github.sh bootstrap
          sh github.sh install_package_control
          sh github.sh run_tests
          sh github.sh run_syntax_tests
