name: Run tests

on:
  push:
    branches:
      - master
  pull_request:

env:
  TRAVIS_OS_NAME: linux

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        st-version: [3, 4]
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config --global user.name GitSavvy
          git config --global user.email gitsavvy@gitsavvy.com
      - uses: SublimeText/UnitTesting/actions/setup@v1
        with:
          sublime-text-version: ${{ matrix.st-version }}
      - uses: SublimeText/UnitTesting/actions/run-tests@v1

  run-syntax-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: SublimeText/UnitTesting/actions/setup@v1
      - uses: SublimeText/UnitTesting/actions/run-syntax-tests@v1
